version: "2"
services:
  test:
    build:
      dockerfile: Dockerfile.ci
      context: .
    command: ["ginkgo -r -v"]
    entrypoint: ["/bin/sh","-c"]
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
